### ISSUE TITLE
cant runt it

### ISSUE THREAD

**Issue by brahmanggi** [fuomag9/ChaturbateBot#18]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "ChaturbateBot.py", line 116, in telegram_bot
    @bot.message_handler(commands=['start', 'help'])
AttributeError: 'TeleBot' object has no attribute 'message_handler'

**Comment by fuomag9** [comment]
Which python version are you using? Did you install all the dipendencies in requirements.txt?

**Comment by brahmanggi** [comment]
yes, already install all, with pip install -r requirements.txt, am i missing something ?

**Comment by fuomag9** [comment]
Did you run it using python3? (Try with 3.5/3.6 if you didn’t)

**Comment by brahmanggi** [comment]
hi, thank you it works, but i've still have this notification 

add
('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
'in <string>' requires string as left operand, not bytes
('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
'in <string>' requires string as left operand, not bytes
('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
'in <string>' requires string as left operand, not bytes
('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
'in <string>' requires string as left operand, not bytes
('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
'in <string>' requires string as left operand, not bytes
('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
'in <string>' requires string as left operand, not bytes
('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
'in <string>' requires string as left operand, not bytes
('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
'in <string>' requires string as left operand, not bytes

is there any solution?

**Comment by fuomag9** [comment]
Which arguments did you pass to the bot? Are you using a functional telegram bot key?(you need to obtain it using @botfather on telegram)

**Comment by brahmanggi** [comment]
yes, i am using it from @botfather

**Comment by fuomag9** [comment]
Which arguments did you pass to the bot?

**Comment by brahmanggi** [comment]
my mistake, this is seems related to my network, its already running well , thank you
